baseURL = 'https://www.abcd-j.de'
languageCode = 'en-us'
title = 'ABCD-J'
theme = "PaperMod"

# see https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-installation/#sample-configyml

[menu]
  [[menu.main]]
    name = "Data"
    url = "https://data.abcd-j.de/"
    weight = 2

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  displayFullLangName = true
  [params.abcdjMode]
    enabled = true
    title = "Accessing Behavior for Clinical Data and Joint Usage"
    subtitle = ""
    imageUrl = "pics/abcdj_logo.svg"
    imageTitle = "abcdj_logo"
    imageHeight = 250
    imageWidth = 1200


# repeat as many times as needed
# icon names -> grep icon_name themes/PaperMod/layouts/partials/svg.html
# [[params.socialIcons]]
#   name = "github"
#   url = "https://github.com/abcd-j"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    title = "ABCD-J"
    languageName = "English"
    weight = 1
  [languages.de]
    title = "ABCD-J"
    languageName = "Deutsch"
    weight = 2
